// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Fixture Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Fixture Test', async function() {
    // Test name: Fixture Test
    // Step # | name | target | value
    // 1 | open | http://localhost:8000/ | 
    await driver.get("http://localhost:8000/")
    // 2 | setWindowSize | 1094x816 | 
    await driver.manage().window().setRect({ width: 1094, height: 816 })
    // 3 | click | linkText=Register | 
    await driver.findElement(By.linkText("Register")).click()
    // 4 | click | linkText=Fixture | 
    await driver.findElement(By.linkText("Fixture")).click()
    // 5 | click | css=.tracking-wide | 
    await driver.findElement(By.css(".tracking-wide")).click()
    // 6 | click | name=tournament_id | 
    await driver.findElement(By.name("tournament_id")).click()
    // 7 | select | name=tournament_id | label=Torneo5
    {
      const dropdown = await driver.findElement(By.name("tournament_id"))
      await dropdown.findElement(By.xpath("//option[. = 'Torneo5']")).click()
    }
    // 8 | click | name=local | 
    await driver.findElement(By.name("local")).click()
    // 9 | select | name=local | label=ContaTeam
    {
      const dropdown = await driver.findElement(By.name("local"))
      await dropdown.findElement(By.xpath("//option[. = 'ContaTeam']")).click()
    }
    // 10 | click | name=visitor | 
    await driver.findElement(By.name("visitor")).click()
    // 11 | select | name=visitor | label=CivilTeam
    {
      const dropdown = await driver.findElement(By.name("visitor"))
      await dropdown.findElement(By.xpath("//option[. = 'CivilTeam']")).click()
    }
    // 12 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 13 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 14 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 15 | click | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).click()
    // 16 | type | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 2021-04-22T12:00
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).sendKeys("2021-04-22T12:00")
    // 17 | type | css=.flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300 | 2021-04-22T12:04
    await driver.findElement(By.css(".flex:nth-child(3) > .mb-2:nth-child(1) > .border-gray-300")).sendKeys("2021-04-22T12:04")
    // 18 | click | name=place_id | 
    await driver.findElement(By.name("place_id")).click()
    // 19 | select | name=place_id | label=Salida Panamericana
    {
      const dropdown = await driver.findElement(By.name("place_id"))
      await dropdown.findElement(By.xpath("//option[. = 'Salida Panamericana']")).click()
    }
    // 20 | click | css=.flex:nth-child(4) .border-gray-300 | 
    await driver.findElement(By.css(".flex:nth-child(4) .border-gray-300")).click()
    // 21 | select | css=.flex:nth-child(4) .border-gray-300 | label=Programado
    {
      const dropdown = await driver.findElement(By.css(".flex:nth-child(4) .border-gray-300"))
      await dropdown.findElement(By.xpath("//option[. = 'Programado']")).click()
    }
    // 22 | click | css=.bg-gray-800:nth-child(2) | 
    await driver.findElement(By.css(".bg-gray-800:nth-child(2)")).click()
    // 23 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 24 | click | css=.text-sm:nth-child(5) .inline-flex:nth-child(1) > .fas | 
    await driver.findElement(By.css(".text-sm:nth-child(5) .inline-flex:nth-child(1) > .fas")).click()
    // 25 | click | name=visitor | 
    await driver.findElement(By.name("visitor")).click()
    // 26 | select | name=visitor | label=AdminTeam
    {
      const dropdown = await driver.findElement(By.name("visitor"))
      await dropdown.findElement(By.xpath("//option[. = 'AdminTeam']")).click()
    }
    // 27 | click | css=.bg-gray-800:nth-child(2) | 
    await driver.findElement(By.css(".bg-gray-800:nth-child(2)")).click()
    // 28 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 29 | click | css=.text-sm:nth-child(5) .inline-flex:nth-child(2) > .fas | 
    await driver.findElement(By.css(".text-sm:nth-child(5) .inline-flex:nth-child(2) > .fas")).click()
    // 30 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
    // 31 | click | css=.swal2-confirm | 
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
