// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Sorteo Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Sorteo Test', async function() {
    // Test name: Sorteo Test
    // Step # | name | target | value
    // 1 | open | http://localhost:8000/ | 
    await driver.get("http://localhost:8000/")
    // 2 | setWindowSize | 1094x816 | 
    await driver.manage().window().setRect({ width: 1094, height: 816 })
    // 3 | click | linkText=Register | 
    await driver.findElement(By.linkText("Register")).click()
    // 4 | click | linkText=Sorteo | 
    await driver.findElement(By.linkText("Sorteo")).click()
    // 5 | click | css=.bg-red-500 | 
    await driver.findElement(By.css(".bg-red-500")).click()
    // 6 | click | css=.bg-red-500 | 
    await driver.findElement(By.css(".bg-red-500")).click()
    // 7 | click | css=.bg-red-500 | 
    await driver.findElement(By.css(".bg-red-500")).click()
    // 8 | click | css=.hover\3A bg-blue-700 | 
    await driver.findElement(By.css(".hover\\3A bg-blue-700")).click()
    // 9 | click | css=div:nth-child(1) > .bg-gray-50 | 
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).click()
    // 10 | type | css=div:nth-child(1) > .bg-gray-50 | 2023-11-17
    await driver.findElement(By.css("div:nth-child(1) > .bg-gray-50")).sendKeys("2023-11-17")
    // 11 | click | name=timeinit | 
    await driver.findElement(By.name("timeinit")).click()
    // 12 | type | name=timeinit | 12:00
    await driver.findElement(By.name("timeinit")).sendKeys("12:00")
    // 13 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 14 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 15 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 16 | type | name=timegame | 48
    await driver.findElement(By.name("timegame")).sendKeys("48")
    // 17 | click | css=.overflow-hidden | 
    await driver.findElement(By.css(".overflow-hidden")).click()
    // 18 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 19 | click | name=timegame | 
    await driver.findElement(By.name("timegame")).click()
    // 20 | type | name=timegame | 92
    await driver.findElement(By.name("timegame")).sendKeys("92")
    // 21 | click | css=.py-5 | 
    await driver.findElement(By.css(".py-5")).click()
    // 22 | click | css=.bg-white:nth-child(1) > td > .w-40 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-40")).click()
    // 23 | click | css=.bg-white:nth-child(1) > td > .w-40 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-40")).click()
    // 24 | click | css=.bg-white:nth-child(1) > td > .w-40 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-40")).click()
    // 25 | click | css=.bg-white:nth-child(1) > td:nth-child(6) | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td:nth-child(6)")).click()
    // 26 | click | css=.bg-white:nth-child(1) > td > .w-24 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-24")).click()
    // 27 | click | css=.bg-white:nth-child(1) > td > .w-24 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-24")).click()
    // 28 | click | css=.bg-white:nth-child(1) > td:nth-child(4) | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td:nth-child(4)")).click()
    // 29 | click | css=.bg-white:nth-child(2) > td:nth-child(4) | 
    await driver.findElement(By.css(".bg-white:nth-child(2) > td:nth-child(4)")).click()
    // 30 | click | css=.bg-white:nth-child(1) > td > .w-40 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-40")).click()
    // 31 | click | css=.bg-white:nth-child(1) > td:nth-child(6) | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td:nth-child(6)")).click()
    // 32 | click | css=.bg-white:nth-child(1) > td > .w-24 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-24")).click()
    // 33 | click | css=.bg-white:nth-child(1) > td > .w-24 | 
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-24")).click()
    // 34 | type | css=.bg-white:nth-child(1) > td > .w-24 | 11:00 pm
    await driver.findElement(By.css(".bg-white:nth-child(1) > td > .w-24")).sendKeys("11:00 pm")
    // 35 | click | css=.max-w-7xl:nth-child(2) | 
    await driver.findElement(By.css(".max-w-7xl:nth-child(2)")).click()
    // 36 | click | css=.bg-white:nth-child(7) .w-40 | 
    await driver.findElement(By.css(".bg-white:nth-child(7) .w-40")).click()
    // 37 | type | css=.bg-white:nth-child(7) .w-40 | Salida Cuzco
    await driver.findElement(By.css(".bg-white:nth-child(7) .w-40")).sendKeys("Salida Cuzco")
  })
})
